files:
  /etc/pki/tls/certs/server.crt:
    content: |
      -----BEGIN CERTIFICATE-----
      MIIFqzCCA5OgAwIBAgIUCIhE5uEqHrnqzYWYgfpZGbt2nsMwDQYJKoZIhvcNAQEN
      BQAwZTELMAkGA1UEBhMCVUsxFDASBgNVBAgMC1dlc3QgU3Vzc2V4MRAwDgYDVQQH
      DAdIb3JzaGFtMRIwEAYDVQQKDAl3YXJyZW5iOTUxGjAYBgNVBAMMEXd3dy53YXJy
      ZW5iOTUuY29tMB4XDTI0MDcyMjA1NDkwOVoXDTI1MDcyMjA1NDkwOVowZTELMAkG
      A1UEBhMCVUsxFDASBgNVBAgMC1dlc3QgU3Vzc2V4MRAwDgYDVQQHDAdIb3JzaGFt
      MRIwEAYDVQQKDAl3YXJyZW5iOTUxGjAYBgNVBAMMEXd3dy53YXJyZW5iOTUuY29t
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvBI1kX2e1BE8nFKrcEIl
      0xvCJUXEPOjtl7M+uTUcZpi6Nlt0UJklVaDBEsewyQMa41eSXQf6MvTWtVXzwBxA
      iVRlFUkk1pXFaicDYiGyrd3mlHbHkZluGSf2ccCYXMtp2XY/7HFBJZeOtZsGOSNE
      A0Gshjv1rkK7q6zk0Ba4uIGr0lL/6lQxQ1i2Q/L+gm/BpfLTm90WOXNSpq6EvdqH
      3IGZtzeDjovwJKIQtHZckSAKvOmPDe0Oy5hNbyAjuANFsDjGn+7OVVquKDE9HWVQ
      v0nb/2a0OYtoj7gejMihH5ijmJAOkZI7pJOBKB2bMqGw1Z1DOJ/8fOrA+IRzxOJm
      vHXyg1WyHEBWjYpiK8KyaRS2QrZ5wKwcGmjTFQVv3Ur7pPNoGQHzrZiq5FRE3Z0M
      Z//grz4xhXTNHJ4MwvEZJ5httMhewu7PPsEdzGXf8wrOIq5Pwk6NrgF4m7bUd9aZ
      JSGskB9fFuiEsaIXaHMRBlaCAN2HAQk6yFd0/7fnIiID1NnccH3guLESsYwFdXcH
      etzzK47K0Exh6GNMQ0HFFQPUCyodSI99ZLq4Fpz1SiUrovIfyeDY4u730HBsU+gK
      strAi1qjgxiVwl/tOglxI+peGE8xHn+aYzT1k6xqg8Jk0g7Kh7KfRjv6bu9Cgdb9
      uilzrkgi5xR7znUyyNxWoMcCAwEAAaNTMFEwHQYDVR0OBBYEFH8Na5xlVqzvo7Xv
      XjXL4bSWjIXvMB8GA1UdIwQYMBaAFH8Na5xlVqzvo7XvXjXL4bSWjIXvMA8GA1Ud
      EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQENBQADggIBAH1sVXvGgcv9seopm7L4RBSM
      S8rMPVNCxf9oCYLNyjrlnCbeeUCPf5prYAMcnhLowUGDH/XxK+92nXdaaUh2+IpC
      +pQQsf7hikz/11TbbWJyHNNAZY+FjxF+WQWR46Q8WpUJBJKD81ni8+Opyz+nlGLK
      prS2ZWp0sNTH1quj0uoR04LnH7H5wa9eNO20bNxGeu14exksWfMH4Ow9Mu7cmyaR
      OnHttjefgUlP9dXqol5FPDBZy82b6AOkqseQh/JqZlByYS8bLmzjT/zOraVJlxa6
      4XkQJ88u32dOk/gVAeVfbwLv6bJGwBxAFtmexz4PXao8zTF05+UdEyLKih6S4gdG
      M+G+2DUxmITjJftJRNN/pXnCpjPkNoNv+vUSrKVrPKkwUqWBR66mLmjLWVMn7xJb
      HDRcqMJ3EMi8jDwZMF+h/sgXee7svEjPA65s6mfaotyctxcLoqMdZgLQW9kCyRux
      0C28yV2yPvm8fqay+NyZfF7HfpsbS1BeBZQ6sKc4W/drTuc9yG60RVp/EME7PWdp
      tt1nYkpXGwgnureOkFngS974OqiRJ1RP0tg7PNYcs1GWUz89FnlCo3StNF2m++ZQ
      7E+NH4OPeW1vcENLiKj9aADx2l6oAmr01E55ma7uYyKlHQgLI/PGbUf1/uNJdM/6
      0EuOsrOpFE478qnxCECj
      -----END CERTIFICATE-----      

container_commands:
  01restart_nginx:
    command: "service nginx restart"
